run:
  timeout: 5m
linters:
  enable:
    - megacheck
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - bodyclose
    - rowserrcheck
    - asciicheck
    - misspell
    - exportloopref
    - dupl
    - goconst
  disable:
    - prealloc
    - gosec
    - lll
