on: [push]
name: lint
jobs:
  golangci:
    runs-on: ubuntu-22.04
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
          version: 1.0
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
